---
- hosts: all
  become: true # Ensures the tasks run with elevated privileges (necessary for package installation and service management).
  tasks:
    - name: install apache2 webserver
      apt: # Uses apt to install the web server on Debian-based systems like Ubuntu.
        name: apache2
        state: present
        update_cache: yes

    - name: start apache2 webserver
      service: # Ensures Apache starts and remains enabled after a reboot.
        name: apache2
        state: started
        enabled: true

    - name: copy file
      copy: # Uses the copy module to deploy a web page to /var/www/html/.
        src: /home/ansible/index.html
        dest: /var/www/html
        user: root
        group: root
        mode: 0644
