---
- hosts: all
  become: true
  tasks:
    - name: install apache2 webserver
      apt:
        name: apache2
        state: present

    - name: start apache2 webserver
      service:
        name: apache2
        state: started
        enabled: true

    - name: copy file
      copy:
        src: /home/ansible/index.html
        dest: /var/www/html
        user: root
        group: root
        mode: 0644
