---
- hosts: localhost
  connection: local

  tasks:
    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "{{ item.name}}"
        key_name: "web-key"
        instance_type: t2.micro
        security_group: default
        region: us-east-1
        aws_access_key: "{{ec2_access_key}}" # From vault as defined
        aws_secret_key: "{{ec2_secret_key}}" # From vault as defined
        network_interfaces_id:
          assign_public_ip: true
        image_id: "{{ item.image }}"
        tags:
          environment: "{{item.name}}"
      loop:
        - { image: "ami-08b5b3a93ed654d19", name: "manage-node-1" }
        - { image: "ami-04b4f1a9cf54c11d0", name: "manage-node-2" }
        - { image: "ami-04b4f1a9cf54c11d0", name: "manage-node-3" }
