---
- hosts: all
  become: yes
  tasks:
    - name: print all ansible gathering facts
      ansible.builtin.debug:
        var: ansible_facts['distribution']
    - name: stop the instance
      ansible.builtin.command: /sbin/shutdown -t now
      when: ansible_distribution == 'Ubuntu'
